edition = "2021"
max_width = 100
newline_style = "Unix"
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = true
use_small_heuristics = "Default"

# The options below require nightly rustfmt. Uncomment if you opt into nightly.
# blank_lines_upper_bound = 2
# format_code_in_doc_comments = true
# group_imports = "StdExternalCrate"
# imports_granularity = "Crate"
# imports_layout = "HorizontalVertical"
# struct_field_align_threshold = 20
# wrap_comments = true
