name: Carcinisation Dev
version: 1.0.0
schema: v1

models:
  - name: GPT-OSS 20B
    provider: ollama
    model: gpt-oss:20b
    roles:
      - chat
      - edit
  - name: Fast Apply 1.5B v1.0
    provider: ollama
    apiBase: http://192.168.1.158:11434
    model: hf.co/dat-lequoc/Fast-Apply-1.5B-v1.0_GGUF:latest
    roles:
      - apply
    defaultCompletionOptions:
      contextLength: 32768
  - name: Qwen2.5 Coder 14B
    provider: ollama
    model: qwen2.5-coder:14b
    roles:
      - rerank
  - name: CodeLlama 7B Code
    provider: ollama
    model: codellama:7b-code
    roles:
      - autocomplete
  - name: Nomic Embed
    provider: ollama
    model: nomic-embed-text:latest
    roles:
      - embed

tabAutocompleteModel: CodeLlama 7B Code
rerankerModel: Qwen2.5 Coder 14B

systemMessage: |
  Assisting on "Carcinisation" (Bevy 0.15 → 0.17).
  Follow .continue/rules. Use Makefile actions. Minimal diffs; compile → behavior → style.

  **Available Tools:**
  - file_glob_search, grep_search, read_file (Continue built-ins)
  - run_shell, env_info (Base MCP)
  - bevy_version, find_bevy_system_like_fns (Bevy MCP)
  - list_rust_files, find_module_doc_gaps, cargo_doc, make (Rust Docs MCP)
  - draft_commit, draft_pr, summarize (Scribe MCP)
  - browser_navigate, browser_click, browser_snapshot (Browser MCP)

  **Paths:** Relative only (`src/main.rs`), NEVER absolute (`/src/main.rs`)
  **Discovery:** file_glob_search/grep_search → read_file → analyze (MCP tools) → propose

tools:
  - server: Toolkit Base MCP
    select: all
  - server: Bevy MCP
    select: all
  - server: Rust Docs MCP
    select: all
  - server: Scribe (Docs & Commits)
    select: all
  - server: Browser (Playwright)
    select: all
